language: java
jdk:
    -openjdk8
script: 
    - ant build
    - sonar-scanner

addons:
    sonarcloud:
        organization: aledifi
        token:
            secure: travis encrypt 9b5c0e5f02273e4a11503319ffc4d8fbb40a4671


