language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "aledifi"
    token:
      secure: 9134a1e4c0d7d9ba3284e8b7d6fef9fa376a7c7b
script:
  - ant build
  - sonar-scanner


